export const ADMIN_NEW_CATEGORY_REQUEST = "ADMIN_NEW_CATEGORY_REQUEST";
export const ADMIN_NEW_CATEGORY_SUCCESS = "ADMIN_NEW_CATEGORY_SUCCESS";
export const ADMIN_NEW_CATEGORY_FAIL = "ADMIN_NEW_CATEGORY_FAIL";

export const ADMIN_NEW_SUBCATEGORY_REQUEST = "ADMIN_NEW_SUBCATEGORY_REQUEST";
export const ADMIN_NEW_SUBCATEGORY_SUCCESS = "ADMIN_NEW_SUBCATEGORY_SUCCESS";
export const ADMIN_NEW_SUBCATEGORY_FAIL = "ADMIN_NEW_SUBCATEGORY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
