export const PARTNER_LOGIN_REQUEST = "PARTNER_LOGIN_REQUEST";
export const PARTNER_LOGIN_SUCCESS = "PARTNER_LOGIN_SUCCESS";
export const PARTNER_LOGIN_FAIL = "PARTNER_LOGIN_FAIL";

export const PARTNER_REGISTER_REQUEST = "PARTNER_REGISTER_REQUEST";
export const PARTNER_REGISTER_SUCCESS = "PARTNER_REGISTER_SUCCESS";
export const PARTNER_REGISTER_FAIL = "PARTNER_REGISTER_FAIL";

export const PARTNER_CREATE_POST_REQUEST = "PARTNER_CREATE_POST_REQUEST";
export const PARTNER_CREATE_POST_SUCCESS = "PARTNER_CREATE_POST_SUCCESS";
export const PARTNER_CREATE_POST_FAIL = "PARTNER_CREATE_POST_FAIL";

export const PARTNER_DETAILS = "PARTNER_DETAILS";
export const NO_PARTNER = "NO_PARTNER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
